name: otomasi deploy server 
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
           cd Altera
           rm -rf deployBE16
           git clone https://github.com/jackpanda96/deployBE16.git
           cd deployBE16
           go run main.go
           
